### ISSUE TITLE
Netcup alerting: Failed systemd units

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#241]
To spot issues such as #239 automatically in the future, we will want to
configure a Prometheus alert that monitors for failed systemd units using the
node exporter.

An example alert for this could look as follows:

```yml
- alert: node/systemd-unit-failed
  expr: node_systemd_unit_state{state="failed", name!="openipmi.service", name!="nvmf-autoconnect.service"} != 0
  for: 15m
  labels:
    severity: warning
  annotations:
    summary: Node unit {{ $labels.name }} has failed (instance {{ $labels.instance }})
```

The two excluded services are services that I've spotted to fail occasionally
on netcup nodes. If this is configured using an Ansible template, we might need
to use the `{% raw %}` template tag to prevent Jinja from interpreting the
double curly braces.
